feat: add api call display current day
Bitmun/apple-weather-app pull request #1
Opened 2024-02-04 12:35 UTC by Bitmun

### Выполнено
- Добавлена логика получения данных с сервера
- Добавлен легкий html/css для отображения данных с сервера
- Небольшое разделение на компоненты
### Скриншоты
- ![image](https://github.com/Bitmun/apple-weather-app/assets/112799457/ed0b2246-c91a-4281-9a8b-38ff3e88b4f1)
Структура проекта: 
- 
### Проблемы / Отсебятина
- Не особо удобный вид данных ответа от сервера, в будущем возможно имениться
- Попытался установить path aliases, не вышло(

2024-02-05 10:36 UTC, PolinaPolina94 commented on src/components/CurrentDayInfo/CurrentDayInfo.tsx
> +          <div className="hour-wrapper">
Хорошо было бы добавить key

2024-02-06 06:23 UTC, fatykhava approved these changes

2024-02-06 06:23 UTC, fatykhava commented on src/api/data.ts
> +export const url = "https://api.open-meteo.com/v1/forecast";
можно и лучше использовать .env для такого

2024-02-06 06:23 UTC, fatykhava commented on src/components/CityCard/CityCard.tsx
> +  const minTemp = dailyData?.temperature2mMin[0].toFixed();
вот такие штуки в целом можно в useMemo оборачивать

2024-02-06 06:23 UTC, fatykhava commented on src/components/CurrentDayInfo/CurrentDayInfo.tsx
> +        const formattedTime = el.toLocaleString("en-US", {
уже было подобное форматирование в CityCard - можно при повторении выделять такие штуки в utils

2024-02-06 06:23 UTC, fatykhava commented on src/components/SideBar/sideBar.css
> +  background-color: aquamarine;
пока ок, но вообще слова для обозначения цветов не используем) только если это переменные

2024-02-06 06:23 UTC, fatykhava commented on src/components/TempBlock/TempBlock.tsx
> +interface TempBlockProps {
я больше за то, чтобы типы лежали в отдельном файле на уровне с компонентой, тогда и компоненты короче и все по полочкам
Это не ошибка ни в коем случае, но для размышления

2024-02-06 06:23 UTC, fatykhava commented on src/components/WeekForecast/WeekForecast.tsx
> +  return (
отделяем пустой строкой все блоки с условиями/циклами/функциями и также перед return тоже лучше оставлять пустую строку для лучшей читаемости кода

2024-02-06 06:32 UTC, fatykhava requested changes

2024-02-06 06:32 UTC, fatykhava commented on src/components/CityCard/cityCard.css
> +.card-wrapper {
используй модульные стили пжлста

2024-02-06 08:13 UTC, merged